
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NewsPaperSBT.Models.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class EmailSettings
{

    public int Id { get; set; }

    public string SmtpHost { get; set; }

    public Nullable<int> SmtpPort { get; set; }

    public Nullable<bool> SmtpEnableSsl { get; set; }

    public string EmailAddress { get; set; }

    public string DisplayName { get; set; }

    public string ReplyEmail { get; set; }

    public string username { get; set; }

    public string Password { get; set; }

}

}
