
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NewsPaperSBT.Models.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class terms
{

    public int versionid { get; set; }

    public Nullable<System.DateTime> datecreated { get; set; }

    public Nullable<bool> isactive { get; set; }

    public Nullable<System.DateTime> datemodified { get; set; }

    public byte[] pdfsrc { get; set; }

    public string fileName { get; set; }

}

}
