
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NewsPaperSBT.Models.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class UserRegion
{

    public int Regionid { get; set; }

    public int Userid { get; set; }

    public string IP { get; set; }

    public string Country { get; set; }

    public string State { get; set; }

    public string City { get; set; }

    public Nullable<bool> Isblock { get; set; }

}

}
