
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NewsPaperSBT.Models.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class User_Test
{

    public int Userid { get; set; }

    public string Fullname { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public Nullable<int> AcountType { get; set; }

    public Nullable<bool> isActive { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public Nullable<System.DateTime> DeletedDate { get; set; }

    public string tokken { get; set; }

    public byte[] FullName_1 { get; set; }

    public string FullName_2 { get; set; }

}

}
