
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NewsPaperSBT.Models.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Vendor
{

    public int Vendorid { get; set; }

    public string Contactname { get; set; }

    public string VendorName { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Street { get; set; }

    public string Email { get; set; }

    public string ZipCode { get; set; }

    public string Phone { get; set; }

    public Nullable<System.DateTime> ContractDate { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string Approvedby { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public Nullable<System.DateTime> DeletedDate { get; set; }

    public Nullable<int> Userid { get; set; }

    public string upccode { get; set; }

    public string DocumentSign { get; set; }



    public virtual Vendor Vendor1 { get; set; }

    public virtual Vendor Vendor2 { get; set; }

}

}
